### ISSUE TITLE
empty directories aren't removed

### ISSUE THREAD

**Issue by spaceone** [univention/git-tools#14] opened 2017-08-30 09:33 UTC
```
$ git checkout 2.0
$ diff -u0 <(svn ls svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-2.0/ucs/base| sed 's#/##g') <(ls -1 base/ | sed 's#/##g')
--- /dev/fd/63  2017-08-30 11:22:15.244558748 +0200
+++ /dev/fd/62  2017-08-30 11:22:15.248558748 +0200
@@ -4,0 +5 @@
+univention-baseconfig
@@ -10,0 +12 @@
+univention-directory-policy
$ find base/univention-directory-policy/ base/univention-baseconfig/
base/univention-directory-policy/
base/univention-directory-policy/conffiles
base/univention-directory-policy/conffiles/etc
base/univention-directory-policy/conffiles/etc/cron.d
base/univention-directory-policy/conffiles/etc/cron.d/.git_keep_empty_dir
base/univention-directory-policy/.git_keep_empty_dir
base/univention-baseconfig/
base/univention-baseconfig/conffiles
base/univention-baseconfig/conffiles/.git_keep_empty_dir
base/univention-baseconfig/debian
base/univention-baseconfig/debian/.git_keep_empty_dir
base/univention-baseconfig/.git_keep_empty_dir
base/univention-baseconfig/etc
base/univention-baseconfig/etc/bash_completion.d
base/univention-baseconfig/etc/bash_completion.d/.git_keep_empty_dir
base/univention-baseconfig/python
base/univention-baseconfig/python/.git_keep_empty_dir
base/univention-baseconfig/python/univention
base/univention-baseconfig/python/univention/.git_keep_empty_dir
base/univention-baseconfig/scripts
base/univention-baseconfig/scripts/.git_keep_empty_dir
```

**Comment by alexklaeser** [comment] 2017-08-30 11:11
This is a duplicate of #5.

**Closed as completed by alexklaeser** 2017-08-30 11:11 UTC
Labels: duplicate
